name: CI/CD Docker PHP App
# Descripción: Este workflow se encarga de construir la imagen Docker de la aplicación PHP, subirla a Docker Hub y desplegarla en un servidor de producción mediante SSH.
on:
  push:
    branches: [ "main" ] # Se activa al subir cambios a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # Tarea 7: Construcción de la imagen (BUILD)
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen a Docker Hub (PUSH)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/actividad61-aplicacion-crud-php:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Tarea 7: Conexión remota por SSH y despliegue (PULL & RUN)
      - name: Desplegar en servidor de producción vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/actividad61-aplicacion-php-produccion [cite: 110]
            docker compose down 
            docker compose pull [cite: 122]
            docker compose up -d [cite: 121]